#------------------------------------------------------------------------------------
# verboseSetup.mac: Set up the verbosity environment
#  [Note] Geant4 Tutorial for Hep/Medicine Users
#------------------------------------------------------------------------------------

## Commonly used verbosity
/run/verbose 1
/tracking/verbose 1

## Miscellaneous verbosity
/control/verbose 0
/event/verbose 0
/material/verbose 0
/process/verbose 0
/vis/verbose 0
