#------------------------------------------------------------------------------------
# primaryGeneratorSetup.mac: Set up the primary generator environment
#  [Note] Geant4 Tutorial for Hep/Medicine Users
#------------------------------------------------------------------------------------

## Particle type
/gun/particle geantino

## Kinematical information
/gun/energy    1.0 MeV
/gun/position  0.0  0.0  -5.0 cm
/gun/direction 0.0  0.0  +1.0
